apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: devops-toolkit
spec:
  components:
    - name: devops-toolkit
      type: webservice
      properties:
        image: vfarcic/devops-toolkit-series
        port: 80
      traits:
        - type: ingress
          properties:
            domain: localhost
            http:
              "/": 80
